version: "3.7"

services:
  test:
    build:
      context: .
    environment:
      - CI=true
    command: yarn test --watchAll=${WATCH-false} --colors
    volumes:
      - "./src:/usr/src/app/src"
  dev:
    build:
      context: .
    ports:
      - 3000-3001:3000-3001
    command: yarn start
    volumes:
      - "./:/usr/src/app" #this copies everything which works but seems dumb
    links:
      - "redis:redis"
  redis:
    image: "redis:alpine"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
